"""Initial migration

Revision ID: 342a7c5b49dd
Revises: 47f95f4ec924
Create Date: 2025-05-11 21:57:27.971802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342a7c5b49dd'
down_revision: Union[str, None] = '47f95f4ec924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_flights_slug'), 'flights', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_slug'), table_name='flights')
    op.drop_column('flights', 'slug')
    # ### end Alembic commands ###
